import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  ...esES,
  userProfile: {
    ...esES.userProfile,
    navbar: {
      ...esES.userProfile?.navbar,
      title: "Configuración",
    },
    start: {
      ...esES.userProfile?.start,
      headerTitle__account: "Datos de la Cuenta",
      profileSection: {
        title: "Foto de Perfil",
        primaryButton: "Editar",
      },
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body
          className={`${inter.className} ${lato.className} text-text-color`}
        >
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
