import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  ...esES,
  userProfile: {
    ...esES.userProfile,
    navbar: {
      ...esES.userProfile?.navbar,
      title: "Configuración",
      account: "Cuenta",
    },
    start: {
      ...esES.userProfile?.start,
      headerTitle__account: "Datos de la Cuenta",
      profileSection: {
        title: "Cuenta",
        primaryButton: "Editar",
      },
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body
          className={`${inter.className} text-text-color overflow-x-hidden`}
        >
          <Providers>
            {children}
            <ToastContainer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
