"use client";

import { Progress, Chip } from "@nextui-org/react";
import { FaCheck, FaCircle, FaBan, FaForward } from "react-icons/fa6";
import { BriefItem } from "@/types/workspaceTypes";

interface BriefProgressProps {
    layer: 1 | 2 | 3;
    completionPercent: number;
    coveredFields: string[];
    /** Checklist dinámico que arma la IA según qué se valúa. */
    briefItems?: BriefItem[];
    /** Identificación del ítem generada por la IA durante el brief. */
    title?: string | null;
    briefComplete: boolean;
}

/** Fallback para valuaciones viejas sin checklist dinámico. */
const LEGACY_FIELDS = [
    { key: "identificacion", label: "Identificación" },
    { key: "estado", label: "Estado" },
    { key: "antiguedad", label: "Antigüedad" },
    { key: "documentacion", label: "Documentación" },
    { key: "mantenimiento", label: "Mantenimiento" },
    { key: "danos", label: "Daños" },
    { key: "mercado", label: "Mercado" },
    { key: "precioReferencia", label: "Precio Ref." },
];

const LAYER_COLORS: Record<number, "warning" | "primary" | "success"> = {
    1: "warning",
    2: "primary",
    3: "success",
};

const STATUS_STYLES: Record<string, { classes: string; icon: React.ReactNode; hint?: string }> = {
    cubierto: {
        classes: "bg-success-50 text-success-700",
        icon: <FaCheck size={10} />,
    },
    no_aplica: {
        classes: "bg-gray-100 dark:bg-slate-800 text-gray-400 line-through",
        icon: <FaBan size={10} />,
        hint: "No aplica",
    },
    omitido: {
        classes: "bg-warning-50 text-warning-600",
        icon: <FaForward size={10} />,
        hint: "Omitido",
    },
    pendiente: {
        classes: "bg-gray-50 dark:bg-slate-800 text-gray-400",
        icon: <FaCircle size={6} />,
    },
};

export default function BriefProgress({
    layer,
    completionPercent,
    coveredFields,
    briefItems,
    title,
    briefComplete,
}: BriefProgressProps) {
    // Con checklist dinámico se muestra ese; si no (valuaciones viejas), los 8 ejes fijos.
    const items: BriefItem[] =
        briefItems && briefItems.length > 0
            ? briefItems
            : LEGACY_FIELDS.map((field) => ({
                  key: field.key,
                  label: field.label,
                  status: coveredFields.includes(field.key) ? "cubierto" : "pendiente",
              }));

    return (
        <div className="space-y-4">
            {/* Title generated by the AI */}
            {title && (
                <p className="text-sm font-semibold text-gray-800 dark:text-gray-200">
                    {title}
                </p>
            )}

            {/* Layer indicator */}
            <div className="flex items-center justify-between">
                <Chip color={LAYER_COLORS[layer]} variant="flat" size="sm">
                    Capa {layer}
                </Chip>
                <span className="text-sm font-medium text-gray-600 dark:text-gray-400">
                    {completionPercent}% completado
                </span>
            </div>

            {/* Progress bar */}
            <Progress
                value={completionPercent}
                color={LAYER_COLORS[layer]}
                size="md"
                className="w-full"
                aria-label="Progreso del brief"
            />

            {/* Dynamic checklist */}
            <div className="grid grid-cols-2 gap-2">
                {items.map((item) => {
                    const style = STATUS_STYLES[item.status] ?? STATUS_STYLES.pendiente;
                    return (
                        <div
                            key={item.key}
                            className={`flex items-center gap-2 text-xs px-2 py-1.5 rounded-md ${style.classes}`}
                            title={style.hint}
                        >
                            {style.icon}
                            <span className="truncate">{item.label}</span>
                        </div>
                    );
                })}
            </div>

            {/* Brief complete message */}
            {briefComplete && (
                <div className="bg-success-50 border border-success-200 rounded-lg p-3 text-center">
                    <p className="text-sm text-success-700 font-medium">
                        ✨ Brief completo — Podés generar el resultado
                    </p>
                </div>
            )}
        </div>
    );
}
